### ISSUE TITLE
[Bug]: Hard-coded path reference in Get-PSProjectReport

### ISSUE THREAD

**Issue by lboening** [jdhitsolutions/PSProjectStatus#9]
### Describe the problem

Get-PSProjectReport fails when the scripts folder is not C:\SCRIPTS. See line 40.

```powershell
Get-PSProjectReport -Path D:\code\Powershell
```

### Expectation

Works if supplied with a folder such as d:\Code\PowerShell

### Additional Information

```powershell
Get-ChildItem: C:\Users\luke_y\Documents\PowerShell\Modules\PSProjectStatus\0.10.0\functions\public\Get-PSProjectReport.ps1:40
Line |
  40 |          $All =  Get-ChildItem -Path C:\scripts -Directory | Get-PSPro …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\scripts' because it does not exist.
```

### PowerShell version

7.3

### Platform

Windows 10 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [ ] You are running PowerShell in an elevated session.
- [ ] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
Barnacles. Sorry about that. I'll have to clean up the hard-coded reference left over from testing.

**Comment by jdhitsolutions** [comment]
Fixed and published v0.10.1 to the PowerShell Gallery. Update the module and try again.

**Comment by lboening** [comment]
I just tried it again, It still not working. Or am I mistaken?

```powershell
PS D:\Code\Powershell> get-psProjectStatus | format-list

   Project: Powershell [D:\Code\Powershell]

Version    : 0.2.3
Status     : Development
Tasks      : {Update readme, Update readme, auto-publish}
GitBranch  : master
LastUpdate : 2023-08-04 09:00:52 AM


PS D:\Code\Powershell> get-psprojectreport -path 'd:\code'

   Name: Powershell [D:\Code\Powershell]

LastUpdate             Status            Tasks                 GitBranch        Age
----------             ------            -----                 ---------        ---
2023-08-04 09:00:52 AM Development       {Update readme, Upd…     master   01.00:52

PS D:\Code\Powershell> get-psprojectreport -path 'd:\code\powershell'
PS D:\Code\Powershell>
```

Does it only work against a parent folder?

**Comment by jdhitsolutions** [comment]
You run `Get-PSProjectStatus` in the folder with the JSON file.  I wrote `Get-PSProjectReport` to be run from the parent folder. In my case, my modules are stored in subfolders under C:\scripts. Each module folder has a psproject.json file. To get my report, I run `Get-PSProjectReport -Path c:\scripts`, which gives me output like this:

![image](https://github.com/jdhitsolutions/PSProjectStatus/assets/12089920/69094a1f-d914-4adc-b914-4ddad297113c)


So yes, the report command expects the parent path to your *projects*.
